//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fateblade.Licenzeee.WPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class DatabaseSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DatabaseSettings defaultInstance = ((DatabaseSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DatabaseSettings())));
        
        public static DatabaseSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseInMemoryDb {
            get {
                return ((bool)(this["UseInMemoryDb"]));
            }
            set {
                this["UseInMemoryDb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSqLiteDb {
            get {
                return ((bool)(this["UseSqLiteDb"]));
            }
            set {
                this["UseSqLiteDb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqLiteDbPath {
            get {
                return ((string)(this["SqLiteDbPath"]));
            }
            set {
                this["SqLiteDbPath"] = value;
            }
        }
    }
}
